

services:
  mongodb:
    build: mongodb/
    image: mern_mongo:1.0
    container_name: mern_mongo
    restart: always
    networks:
      - web_network
    volumes:
      - ./mongodb/data:/data/db
  nodejs:
    depends_on:
      - mongodb
    build: nodejs/
    #image: mern_nodejs:1.0
    image: mern_nodejs:1.0
    container_name: mern_nodejs
    restart: always
    networks:
      - web_network
    volumes:
      - /usr/app/node_modules
      - ./nodejs:/usr/app
    ports:
      - 3000:3000
    environment:
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=1234
      - DATABASE_HOST=mongodb
  reactjs:
    depends_on:
      - mongodb
    build: frontend/
    #image: mern_reactjs:1.0
    image: mern_reactjs:1.0
    container_name: mern_reactjs
    restart: always
    networks:
      - web_network
    volumes:
      - /usr/app/node_modules
      - ./frontend:/usr/app
    ports:
      #- 8181:80
      - 80:80
      

networks:
  web_network:
    name: mernstack
    driver: bridge
